### ISSUE TITLE
Clarify the listconfig response for securityInheriting.vbtc.autoMineRounds

### ISSUE THREAD

**Issue by Leonardiae** [VeriBlock/vbk-ri-btc#163]
I think the automineround settings can be improved when using listconfig:
```
listconfig
Configuration Properties:
...
        securityInheriting.vbtc.autoMineRounds=[
    # .\application.conf: 15
    1,
    # .\application.conf: 15
    2,
    # .\application.conf: 15
    4
]
```
I was expecting to see something like this instead: securityInheriting.vbtc.autoMineRounds=[1,2,4]

**Comment by Warchant** [comment]
As I recall, @PCasafont mentioned that listconfig does not support printing/assigning of arrays (yet).

**Comment by BernatCarbo** [comment]
Solved at https://github.com/VeriBlock/nodecore/commit/77e6134fadeffcb3af4efe662a5e4475ee5312ef
