### ISSUE TITLE
Api returns error 500 when running api/miner/mine & 20 running operations exist

### ISSUE THREAD

**Issue by Leonardiae** [VeriBlock/vbk-ri-btc#166]
When there are already 20 operations running, the api/miner/mine command returns a 500 error.
I expect a response with a failed and a reason like: There are 20 other operations in progress

**Comment by BernatCarbo** [comment]
It displays the next message:
```
curl -X POST "http://localhost:8080/api/miner/mine" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"chainSymbol\":\"btc\",\"height\":0}"
{
  "message" : "Unable to mine: There are 20 other operations in progress! Please, wait for at least one of them to submit the PoP transaction."
}
```

**Comment by Leonardiae** [comment]
Hmm yes with that curl command I get the same response. 

But when I call this C# function I't successfull when less than 20 operations are running but with 20 running operations I get this exception: "The remote server returned an error: (500) Internal Server Error."

```
        static public void callPoPMinerApi()
        {
            string apiUrl = "http://localhost:8080/api/miner/mine";
            string json = "{\"chainSymbol\": \"vbtc\",\"height\": 0}";
            using (var webClient = new WebClient())
                try
                {
                    webClient.Headers.Add("Content-Type", "application/json");
                    var response = webClient.UploadString(apiUrl, "POST", json);
                }
                catch (Exception exception)
                {
                    log.Error($"Exception: {exception}");
                }
        }
```

**Comment by BernatCarbo** [comment]
Looks like that's a problem on your c# code... Try something like this:
```
static public void callPoPMinerApi()
        {
            string apiUrl = "http://localhost:8080/api/miner/mine";
            string json = "{\"chainSymbol\": \"vbtc\",\"height\": 0}";
            using (var webClient = new WebClient())
                try
                {
                    webClient.Headers.Add("Content-Type", "application/json");
                    var response = webClient.UploadString(apiUrl, "POST", json);
                }
                catch (WebException exception)
                {
                    var response = new StreamReader(exception.Response.GetResponseStream()).ReadToEnd();
                    log.Error("Exception: " + response+". " + exception);
                }
        }
```
That's because we're standardizing the error messages into json objects rather than just strings.

**Comment by Leonardiae** [comment]
Thanks. That works in the sense that I see the message but I was not expecting an 500 error code but rather a 200 code with the message in the response json. 

But I read here [(link)](https://stackoverflow.com/questions/27921537/returning-http-200-ok-with-error-within-response-body) that this is debatable so I leave that for the team to decide, if you say this is OK, then I'm fine with it :)

**Comment by BernatCarbo** [comment]
Yes, we will standardize the error codes soon :).
