### ISSUE TITLE
After vBitcoin is stopped the .lock file is not deleted

### ISSUE THREAD

**Issue by Leonardiae** [VeriBlock/vbk-ri-btc#176]
After stopping vBitcoin the .lock file is not deleted from the testnet3 folder. I tried shutting down vBitcoin-qt with the X (top right) and with [File] [Exit]. Also tried vBitcoind shutting down with Ctrl-C and with vBitcoin-cli -stop, but the .lock file is not deleted.

I'm running Windows 10 btw.

**Comment by Warchant** [comment]
Reopen if this still persists.
