### ISSUE TITLE
vbitcoinqt does not show it's working on comparePopScore while syncing

### ISSUE THREAD

**Issue by Leonardiae** [VeriBlock/vbk-ri-btc#177]
After vBitcoinQt is started it's reindexing blocks on disk for a few minutes and after that shows the status (right below): Up to date. Processed 1545 block(s) of transaction history. It looks like it's ready and only if you run getdebuginfo in the APM do you know that it's not. Apparently the node is still doing something. After a while (~20 minutes) it starts Processing blocks on disk and when this is finished the node is ready.

When you run vBitcoinD you see that after reindexing blocks on disk it starts working on comparePopScore for VBK blocks. This takes about 20 minutes and after that vBitoinQt starts Processing blocks on disk.

Can BitcoinQt show that it's working on comparePopScore?

**Comment by overcookedpanda** [comment]
I will look into this on the QT side, but it's possible that it affects more than just the QT wallet.  I noticed that `getblockcount` was sometimes returning `0` during this period as well.

**Comment by overcookedpanda** [comment]
As an update @Leonardiae I've added this to the beta milestone, and confirmed your findings that the daemon is not considering that additional time is needed for full sync.  It affects vbitcoind as well as vbitcoin-qt

**Comment by Warchant** [comment]
Solved
