### ISSUE TITLE
Remove brackets from message

### ISSUE THREAD

**Issue by Leonardiae** [VeriBlock/vbk-ri-btc#178]
May I suggest to remove the brackets from this message, because it's making it easier to prevent a mistake where someones could copy the ] and it makes it a bit easier to copy the address.

```
2020-06-12 10:03:21 si-poll    WARN  SecurityInheritingMonitor - Error when polling SI Chain (vbtc): Miner is not ready: [PoP wallet does not contain sufficient funds
         Current balance: 0.00000000 tVBK
         Minimum required: 0.10000000, need 0.10000000 more
         Send tVBK coins to: V2uEoUV9QUgd7J7AFgYBeJmptDju3q]
```

**Comment by BernatCarbo** [comment]
Solved with https://github.com/VeriBlock/nodecore/commit/682c6eb08c201a03ea786c35ba119f5d0343c5c7
