### ISSUE TITLE
APM marked as ready while vBitcoin still syncing

### ISSUE THREAD

**Issue by Leonardiae** [VeriBlock/vbk-ri-btc#181]
vBitcoin syncing takes are while at the moment. If you start an APM (for example with running operations) the miner is marked as ready despite being connected to a vBitcoin node which is not done syncing. 

`2020-06-12 09:03:01.265+0200 INFO [event-listener] o.v.m.p.s.AltchainPoPMiner [AltchainPopMinerService.kt:107] Miner is ready!`

After this the APM starts trying to connect to vBitcoin to update the status of the running operations which then runs into errors because no connection can be made yet.

**Comment by BernatCarbo** [comment]
Solved with https://github.com/VeriBlock/nodecore/commit/682c6eb08c201a03ea786c35ba119f5d0343c5c7

**Comment by Leonardiae** [comment]
Thanks!
