### ISSUE TITLE
Unable to load suspended operations after upgrading 

### ISSUE THREAD

**Issue by Leonardiae** [VeriBlock/vbk-ri-btc#189]
After upgrading from altchain-pop-miner-0.4.9-rc.5.dev.12 to altchain-pop-miner-0.4.9-rc.5.dev.26 by copying:
- altchain-pop-miner.db
- vbk-testnet.spvchain.spvchain
- vbk-testnet.txmon
- vbk-testnet.wallet

I get this error
`2020-06-13 09:39:02 main       ERROR AltchainPoPMiner          - Unable to load suspended operations: Expected wire type 2, but found 0`

**Comment by Leonardiae** [comment]
I had to delete altchain-pop-miner.db to fix this error.

**Comment by BernatCarbo** [comment]
That's because we did breaking changes during the beta release, is not intended to happen after the first final release of APM.

**Comment by Leonardiae** [comment]
Ok, thanks for your response.
