### ISSUE TITLE
Add a command like viewrecentrewards

### ISSUE THREAD

**Issue by Leonardiae** [VeriBlock/vbk-ri-btc#199]
Can you please add a command like viewrecentrewards on VPM which shows at least the endorsed block, the altchain, (projected) reward and in which block it's paid and if possible the VBK fee paid.

**Comment by BernatCarbo** [comment]
Solved with https://github.com/VeriBlock/nodecore/commit/92a3b568e65d824bedff5b7566ce3535f7f72fb0

For that case the command would be: listoperations completed
