### ISSUE TITLE
Wait with submitpop until node is synced / connection success

### ISSUE THREAD

**Issue by Leonardiae** [VeriBlock/vbk-ri-btc#216]
I noticed a node being almost 10 blocks behind. Now and then a block is added but the node seems not to be able to catch up to the tip again. In the mean time the APM tries and retries to call the submitpop rpc which keeps failing. Only after I closed the APM was the node able to catch up in ~15 minutes.

Don't know if this is possible but maybe it's better to wait with submitrpc until the node is synced again? Getdebuginfo shows no succes but failed. 

```
getdebuginfo
Running several checks, this may take a few moments...
{
  "information": [
    "SUCCESS - NodeCore connection: Connected",
    "SUCCESS - NodeCore synchronization status: Synchronized (LocalHeight=613296 NetworkHeight=613293)",
    "FAIL - vBitcoin connection: Not connected",
    "FAIL - Unable to determine the vBitcoin synchronization status",
    "SUCCESS - vBitcoin configured payoutAddress 'tb1qugxxu2jua78q33qctxgavsuka0ppyxf8n9vaut' is valid.",
    "SUCCESS - The tVBK PoP wallet contains sufficient funds, current balance: 17.12824000 tVBK"
  ]
```

Not sure if submitrpc failing is cause or effect of the delayed sync. But maybe its best to only try submitpop when the node is in sync again.

**Comment by BernatCarbo** [comment]
This seems to be related with the node, at the APM side we could add some checks to be sure that the node is fully ready to receive any rpc call, but still the node should be able to handle it, @Warchant what do you think?

**Comment by Warchant** [comment]
@BernatCarbo there's no way to determine if node is syncd besides one I described you already :( 

We can improve UX if we block `getpopdata` rpc call until the InitialBlockDownload is false (will be added shortly)

**Comment by Warchant** [comment]
@BernatCarbo it is already there https://github.com/VeriBlock/vbk-ri-btc/blob/6578933f0d1bc7a3f728e1b7b20899ffe15ed502/src/vbk/rpc_register.cpp#L137

We can't do better sync check than current.

**Comment by BernatCarbo** [comment]
At the APM side, we added a node check before each APM task, that should help as well: https://github.com/VeriBlock/nodecore/commit/76861e8410b8ca15e59466b7504961f195477809
