### ISSUE TITLE
Long warning when user forgets to set payout address

### ISSUE THREAD

**Issue by Leonardiae** [VeriBlock/vbk-ri-btc#243]
When you forget to set the payout address, which is by default set to a placeholder text, a long warning 

`2020-07-11 10:52:29 main       WARN  PluginService             - Unable to load plugin vbtc (btc impl) from config: Invalid segwit address: generatePayoutScriptFromSegwitAddress cannot be called with an address which isn't the length of 39 or 59 + hrp + 1! Provided address: INSERT PAYOUT ADDRESS, hrp: INSERT PAYOUT ADDRESS`

Maybe it's possible to catch this warning in case the payoutAddress is set to the placeholder text and then show a message that the user should change the payout address first.

**Comment by BernatCarbo** [comment]
Solved with https://github.com/VeriBlock/nodecore/commit/6076beb9b38381f27b1bebc31fea42d9024abda3
