### ISSUE TITLE
APM does not respond to CTRL-C (on Windows)

### ISSUE THREAD

**Issue by Leonardiae** [VeriBlock/vbk-ri-btc#244]
Nodecore and the VPM can be shutted down gracefully with CTRL-C. But the APM does not (seem to) respond to this command.

**Comment by BernatCarbo** [comment]
It behaves like the VPN for me, it shuts down when CTRL+C is pressed, can you recheck it?

**Comment by Leonardiae** [comment]
When I press CTRL-C the only reponse is that the cursor jumps to the next line, but the APM stays active. Also after waiting for like 10 minutes.

**Comment by Warchant** [comment]
@Leonardiae are you using docker image?

**Comment by Leonardiae** [comment]
Nope, just running it on Windows 10.

**Comment by Leonardiae** [comment]
Using latest APM altchain-pop-miner-0.4.10-dev.82, this works.
