### ISSUE TITLE
Ony segwith / bech32 addresses are supported as payoutaddress

### ISSUE THREAD

**Issue by Leonardiae** [VeriBlock/vbk-ri-btc#252]
Just posting this to make sure this works as intended: is it correct that the payout address has to be a bech32 address, and a native address is not supported?

`2020-07-17 08:33:09 main       WARN  PluginService             - Unable to load plugin vbtc (btc impl) from config: Invalid segwit address: generatePayoutScriptFromSegwitAddress cannot be called with an address which isn't the length of 39 or 59 + hrp + 1! Provided address: 2MzatMWxa6Ccf2VeHqpvSthyrJD4fkZg14r, hrp: 2MzatMWxa6Ccf2VeHqpvSthyrJD4fkZg`

**Comment by Warchant** [comment]
That should be fixed.
