### ISSUE TITLE
vBitcoin not listening to rpcport setting in config file

### ISSUE THREAD

**Issue by Leonardiae** [VeriBlock/vbk-ri-btc#301]
In vBTC-alpha-master.138-4786392 the -rpcport parameter is not in the vbitcoin.config file anymore. When added and changed to another port the default 18332 port is still being used despite a different port being set in the config file.

**Comment by Warchant** [comment]
```
[test]
port=18333
rpcport=18332
```

This setting is section-specific, so you should change it in according section (test/regtest)

**Comment by Leonardiae** [comment]
Yes you are right. Thanks, I learned something, again :)
