### ISSUE TITLE
listoperations does not show more than 50 operations

### ISSUE THREAD

**Issue by Leonardiae** [VeriBlock/vbk-ri-btc#306]
listoperations does not show more than 50 operations, is there a way to see all of them or at least all that are running (not paid yet)?

**Comment by Leonardiae** [comment]
If it's not possible to show more than x operations I would prefer the most recent operations to be shown first. That way if not all operations can be shown some of the older ones are not displayed instead of the latest.

**Comment by BernatCarbo** [comment]
Solved with: https://github.com/VeriBlock/nodecore/commit/f839a4e30112e6f131c99e5387daddc4088ece7b, now you can pass the limit & offset to display the operations (same as in the API)

**Comment by Leonardiae** [comment]
Great, thanks!
