### ISSUE TITLE
Transactiondetails missing from gettransaction

### ISSUE THREAD

**Issue by Leonardiae** [VeriBlock/vbk-ri-btc#375]
Bot on nodecore_cli and the api are the transaction details missing in the response from gettransaction:

```
gettransaction B5812F2EEFB71F3AECD5A1848E1C6D534D3DA3E31E8023E2743CBB7271D9A087
gettransaction B5812F2EEFB71F3AECD5A1848E1C6D534D3DA3E31E8023E2743CBB7271D9A087
{
  "transactions": []
}
```

**Comment by Leonardiae** [comment]
Hmm, not all responses are empty, but most are. Maybe regular transactions work, but only endorsement transactions created by APM return empty?

```
gettransaction C20D7E0CC1C4E4C36D6A0B5365A715C4BE0C0405E7D9A087051750C78BA84352
gettransaction C20D7E0CC1C4E4C36D6A0B5365A715C4BE0C0405E7D9A087051750C78BA84352
{
  "transactions": [
    {
      "timestamp": 1604758742,
      "blockNum": 1007269,
      "confirmations": 2,
      "transaction": {
        "size": 97,
        "txid": "C20D7E0CC1C4E4C36D6A0B5365A715C4BE0C0405E7D9A087051750C78BA84352",
        "data": "",
        "type": "standard",
        "fee": "0.00097001",
        "timestamp": 1604758747,
        "source_amount": "82.50048500",
        "merkle_path": "",
        "source_address": "VDXhjin79TH7VtFZWzauL8EtnCCjcu",
        "bitcoin_transaction": "N/A",
        "bitcoin_block_header_of_proof": "N/A",
        "endorsed_block_header": "N/A",
        "outputs": [
          {
            "address": "V5mmGor5aZ2Xn4RmZbQpHEGGG9kfKA",
            "amount": "0.82500485"
          },
          {
            "address": "VHoWCZrQB4kqLHm1EoNoU8rih7ohyG",
            "amount": "81.67451014"
          }
        ]
      },
      "endorsedBlockHash": "",
      "bitcoinBlockHash": "",
      "bitcoinTxID": "",
      "bitcoinConfirmations": 0
    }
  ]
}
```

**Comment by Leonardiae** [comment]
This is one with data but has details, I don't know the difference :)

gettransaction 1153FC6682D84A3528FB196BB51CA0A6352D800B8CA4DC8EC2E81A2C75D0B8F4
gettransaction 1153FC6682D84A3528FB196BB51CA0A6352D800B8CA4DC8EC2E81A2C75D0B8F4
{
  "transactions": [
    {
      "timestamp": 1604759842,
      "blockNum": 1007303,
      "confirmations": 95,
      "transaction": {
        "size": 248,
        "txid": "1153FC6682D84A3528FB196BB51CA0A6352D800B8CA4DC8EC2E81A2C75D0B8F4",
        "data": "033AE6CA015000000820C7F9AA1CDE001B8BA2D81B8CC7FADD3FF6C64F6CCD52E1BC7C3D77E0000000000ADFD5C8F92CAEDF3E9BE7C8D291FA7B3C7F4AB0554E278A95216E918395186EDB97A65FFFFF7F1DC6568600016400001F423717562456BE894CCB09490F4D787051E1075D79FD6BA853D1C1F1C400000000CE8AACC44585115E6473722BDB01CED93F8107416C3317769A143B1403000000869304288CA586B082EDFF70DDBAB1E6A903040C9EDBB913E838ACB5B1FD8E0D011600146ADA611870E41AEF3F19E15257537D272E153C15",
        "type": "standard",
        "fee": "0.00258168",
        "timestamp": 1604759897,
        "source_amount": "0.00258168",
        "merkle_path": "",
        "source_address": "VDxT86FCLGZDtGmRV7pjgvJSP6QFfz",
        "bitcoin_transaction": "N/A",
        "bitcoin_block_header_of_proof": "N/A",
        "endorsed_block_header": "N/A",
        "outputs": []
      },
      "endorsedBlockHash": "",
      "bitcoinBlockHash": "",
      "bitcoinTxID": "",
      "bitcoinConfirmations": 0
    }
  ]
}

**Comment by Leonardiae** [comment]
Very weird, often I get all details but not allways but when I try later I get the details:

leonard@leonard:~$ curl -d '{"jsonrpc": "2.0","method": "gettransactions","params": {"searchLength": 1000,"ids": ["B5812F2EEFB71F3AECD5A1848E1C6D534D3DA3E31E8023E2743CBB7271D9A087"]},"id": 1}' -H "Content-Type: application/json" -X POST http://localhost:10620/api
{"jsonrpc":"2.0","result":{"success":true},"id":1}

leonard@leonard:~$ curl -d '{"jsonrpc": "2.0","method": "gettransactions","params": {"searchLength": 1000,"ids": ["B5812F2EEFB71F3AECD5A1848E1C6D534D3DA3E31E8023E2743CBB7271D9A087"]},"id": 1}' -H "Content-Type: application/json" -X POST http://localhost:10620/api
{"jsonrpc":"2.0","result":{"transactions":[{"transaction":{"type":"STANDARD","sourceAddress":"VDxT86FCLGZDtGmRV7pjgvJSP6QFfz","sourceAmount":"258416","transactionFee":"258416","data":"033AE6CA015000000820C7F9AA1CDE001B8BA2D81B8CC7FADD3FF6C64F6CCD52E1BC7C3D77E0000000000ADFD5C8F92CAEDF3E9BE7C8D291FA7B3C7F4AB0554E278A95216E918395186EDB97A65FFFFF7F1DC6568600016400001F423717562456BE894CCB09490F4D787051E1075D79FD6BA853D1C1F1C400000000CE8AACC44585115E6473722BDB01CED93F8107416C3317769A143B1403000000869304288CA586B082EDFF70DDBAB1E6A903040C9EDBB913E838ACB5B1FD8E0D011600146ADA611870E41AEF3F19E15257537D272E153C15","timestamp":1604759899,"size":248,"txId":"B5812F2EEFB71F3AECD5A1848E1C6D534D3DA3E31E8023E2743CBB7271D9A087"},"confirmations":209,"blockNumber":1007303,"timestamp":1604759842,"blockHash":"000000068EB5DA886F9FDD3160CDB861FA5A2A8249B4A2F4","merklePath":"1:1:B5812F2EEFB71F3AECD5A1848E1C6D534D3DA3E31E8023E2743CBB7271D9A087:1153FC6682D84A3528FB196BB51CA0A6352D800B8CA4DC8EC2E81A2C75D0B8F4:91195CB8C79035CFB60A354BAB2A473558C9D366A0F81E426DECE48BFF36596E:4952EB28E9EAD9836014A51A87F2BB8067891572D331B21921708B84AFDF63E1:53AFB755A85C87C4010DA6F84F3B4C2E85FF754649BBFEFAB8F81F3B79D6B9EA:19B30AEC7AE3251D570A9C8B9DA733A2474D00F3503F84AF7440DFE4579D2124:24217C85385052F44D6A6D074462B258403C4C2BA4E0307974D9D020EFACD7C8"}],"success":true},"id":1}

**Comment by Leonardiae** [comment]
Maybe it has something to do with searchLength, can someone give advice on how to set this parameter?
Today this same command did not come with a result again but when I incread searchLength to 100000 it does find a result but it takes minutes.

I used to search with searchLength 1 and always got the details almost immediately but this seems different now.

**Comment by Leonardiae** [comment]
But CLI still does not find the transaction:
```
(VBK_CLI rpc (127.0.0.1:10520)) > gettransaction 5AF684634384C801CF65F61D764E9D840EED7E1E3C85164577C7736F02127A0B 100000
gettransaction 5AF684634384C801CF65F61D764E9D840EED7E1E3C85164577C7736F02127A0B 100000
{
  "transactions": []
}
```

**Comment by PCasafont** [comment]
It has always been like that. However, we plan to improve the gettransactions performance with a transaction index. I'll close this for now, though.
