### ISSUE TITLE
Unable to find transaction 5379583AED64901D8E2BA7EC6D61B9BA206491EDCFF75F03641C730320ED8E58 in the monitored address

### ISSUE THREAD

**Issue by Leonardiae** [VeriBlock/vbk-ri-btc#404]
Operation failed because of reason: Unable to find transaction 5379583AED64901D8E2BA7EC6D61B9BA206491EDCFF75F03641C730320ED8E58 in the monitored address

But the transaction can be found on the blockchain: https://testnet.explore.veriblock.org/tx/5379583AED64901D8E2BA7EC6D61B9BA206491EDCFF75F03641C730320ED8E58

 > getoperation phl3f40d3cc
getoperation phl3f40d3cc
Operation data:
{
  "operationId": "phl3f40d3cc",
  "chain": "PHL",
  "state": "Failed",
  "blockHeight": 1369,
  "task": "",
  "stateDetail": {
    "expectedRewardBlock": "1419",
    "chainIdentifier": "4276994270",
    "publicationDataHeader": "0000082097245D66AAA00EF644EA0A97A9E71BB99BA30E7B9C51BC76F9A6E9C508000000B50A5BD3737931FDEAB9AEDB7DA86985911D90471C0137B67D1678642FBFCB385A6BD25F63FC131DC5D4C103",
    "publicationDataContextInfo": "0000055995E8C8CDB70BA98220415561472764D3FB7589676DFA965256C7CE150F000000055AD5CD971391AE3E765E01265FDC414C544009A254EA3664970A6310000000944236326977C307F0CAA6C767346CF26964E5D45B238FA942B26945DACECBD0",
    "publicationDataPayoutInfo": "0014033EC21AE5C5671F8DC19D5848762E05F059274E",
    "vbkContextBlockHashes": "00000005C9FFD8ED782F8BE3AF3F1B66BBCF7E0D2104F8E3, 000000011635EBC88F651C5B399ED2B652CD65BBB1D85B34, 00000004F32B023E788ADACFD95920981EBCA20406D58A02, 000000002D4A6512E0470043BE059D2E047A2397A1AE5B2A, 0000000109FBF12A178A75E53F330D51A4D3E93F358C6B1D, 000000018B1CF0BCEA15883293E1B5F8BFF654C9E6360A80, 000000056B56E3FAC777543F14DF5BE62FC2FC99454B505E, 000000003A695A0C4189679D7632115F40033486AE36F1AA, 0000000006F351C942060236168BCF133A494CCD1B3FA893, 00000006992EB08E06DA731AD7869B204E8FE6FD63DEE000, 000000053C72CFD69B151ECEB2E5C8D22A516098589AFC49, 000000004DC45C234E26F71D640E8F7029AFDECB7260424C, 000000069E40A0AFF986D8EAE2612ABA605D71500C4B4D6B, 00000005D4AD588E4EE84412068813496B6E1E65748B1360, 0000000431621F97E24DFA90FA3E592070DC4FE3778FD294, 000000011C7F5FCB32B9C1B8201B241359860790EFC287D0",
    "btcContextBlockHashes": "0000000000000014B0883DE061950534C58E4E38ABD3A305F0AA801C56E95B92, 000000000000003B26EF5BBC993202ED26890DA8094468B0A1C8FE616A264590, 0000000000000007BF2AE277B87535472BC0F2B387EF7AD28B16B735C03A9712, 000000000000002F641FA08ECBDE42700A9297FAD813CDF0A5DFA49AA97B6139, 0000000000000013C63658D1779D21ED8B416D976874F4B57799CD72707EA3C9, 000000000000002357864C72A4651FDCE6B3BE5FDAA5A7B4AAD827F58CCD7FA1, 000000000000003706F0CF1E8D31499EA7B8695770AD6EA3DC099FDF244FA276, 0000000000000036946AA0FF3EEAC32A98284A6973AF11974B6A505B25BC041A, 0000000000000023CAE8F46D50BCBDD1F68F650306AE17F6001DF917F7564316, 000000000000002DC5DE0FAC440335A4CC8650A744742010BE2D808BB1401A67, 0000000000000015B210D1D18047B45DEC8344F78EBF377531CBDC6C8D2BF730, 0000000000000010AB1FCCF75546505494BC478908570B4F5B9E9028D86D299B, 0000000000000003787F0ADD11BB558ACBDE0DAB86C6B0BD4520B2AF5363F9B6, 0000000000000027D1B38D4C821B6CE723367F8C666C4076F26DEF7576C245F2, 0000000000000016DDA9DE5E2E3A731841265B5FD8589C4F38F1BAC1B2734F6D, 000000000000002C71CB8908F64386345B47A15A9A02A162359BF13B276D4258",
    "failureReason": "Unable to find transaction 5379583AED64901D8E2BA7EC6D61B9BA206491EDCFF75F03641C730320ED8E58 in the monitored address"
  }
}
Operation workflow:
DONE      1. START                           Created APM operation id: phl3f40d3cc
DONE      2. RETRIEVE_MINING_INSTRUCTION     Endorsed PHL block height: 1369
FAILED    3. SUBMIT_ENDORSEMENT_TRANSACTION  Unable to find transaction 5379583AED64901D8E2BA7EC6D61B9BA206491EDCFF75F03641C730320ED8E58 in the monitored address
          4. CONFIRM_ENDORSEMENT_TRANSACTION
          5. DETERMINE_BLOCK_OF_PROOF
          6. PROVE_ENDORSEMENT_TRANSACTION
          9. SUBMIT_POP_TRANSACTION
         10. CONFIRM_ATV
         11. WAIT_FOR_PAYOUT_BLOCK
         12. COMPLETED

**Comment by Mr-Leshiy** [comment]
This problem related to the Nodecore. `Step 3` it is submitting transaction in the VeriBlock blockchain.
