### ISSUE TITLE
Spendable Block high is lower than the current block 

### ISSUE THREAD

**Issue by Davbit1** [VeriBlock/vbk-ri-btc#574]
Spendable in block # or later looks to be lower than the blocks themselves 

https://testnet.explore.vbtc.veriblock.org/tx/bc6f96d69a53f4cc8f66f0ac40abd661d6a8abf917d0964600ac489c3442b9ce
Block 49.450
Spendable in block #49,385 or later

Why that ?

**Comment by Warchant** [comment]
@Davbit1 can easily be explorer display error.
