### ISSUE TITLE
Potential deadlock detected assertion failure 

### ISSUE THREAD

**Issue by Mr-Leshiy** [VeriBlock/vbk-ri-btc#594]
btcsq_1     | 2021-10-28T16:27:21Z UpdateTip: new best=ALT:7903:00000000000000578a3c6d8b03e5ee1ec2f8015cdbe3e9968fdbd32cf03cd397 VBK:2634157:00000000035a8366ed85cb66b1ed8cc235db0ce792a276f5 BTC:706857:00000000000000000000e4030d68c494269691│··············
70097f8492c2563b7f9173e884 version=0x20080000 log2_work=68.381878 tx=8908 date='2021-10-28T16:26:52Z' progress=0.999970 cache=8.7MiB(64168txo)                                                                                                 │··············btcsq_1     | 2021-10-28T16:28:01Z POTENTIAL DEADLOCK DETECTED                                                                                                                                                                                 │··············
btcsq_1     | 2021-10-28T16:28:01Z Previous lock order was:                                                                                                                                                                                    │··············btcsq_1     | 2021-10-28T16:28:01Z  pnode->cs_sendProcessing net.cpp:2029 (in thread msghand)                                                                                                                                                  │··············
btcsq_1     | 2021-10-28T16:28:01Z  cs_main net_processing.cpp:3682 (TRY) (in thread msghand)                                                                                                                                                  │··············btcsq_1     | 2021-10-28T16:28:01Z  pto->cs_inventory net_processing.cpp:3898 (in thread msghand)                                                                                                                                              │··············
btcsq_1     | 2021-10-28T16:28:01Z  (1) pto->m_tx_relay->cs_tx_inventory net_processing.cpp:3912 (in thread msghand)                                                                                                                           │··············btcsq_1     | 2021-10-28T16:28:01Z  pto->m_tx_relay->cs_filter net_processing.cpp:3984 (in thread msghand)                                                                                                                                     │··············
btcsq_1     | 2021-10-28T16:28:01Z  (2) cs txmempool.cpp:817 (in thread msghand)                                                                                                                                                               │··············btcsq_1     | 2021-10-28T16:28:01Z Current lock order is:                                                                                                                                                                                      │··············
btcsq_1     | 2021-10-28T16:28:01Z  m_cs_chainstate validation.cpp:2899 (in thread msghand)                                                                                                                                                    │··············btcsq_1     | 2021-10-28T16:28:01Z  cs_main validation.cpp:2916 (in thread msghand)                                                                                                                                                            │··············
btcsq_1     | 2021-10-28T16:28:01Z  (2) ::mempool.cs validation.cpp:2916 (in thread msghand)                                                                                                                                                   │··············btcsq_1     | 2021-10-28T16:28:01Z  cs_vNodes ./net.h:215 (in thread msghand)                                                                                                                                                                  │··············
btcsq_1     | 2021-10-28T16:28:01Z  (1) m_tx_relay->cs_tx_inventory ./net.h:972 (in thread msghand)                                                                                                                                            │··············btcsq_1     | Assertion failed: detected inconsistent lock order at sync.cpp:119, details in debug log.                                                                                                                                        │··············
btcsq_1     | Aborted (core dumped)

**Comment by Warchant** [comment]
What is the status? @Mr-Leshiy

**Comment by Warchant** [comment]
Low priority because it is no longer shows up. Test is not implemented on a fix yet.

**Comment by Mr-Leshiy** [comment]
It appears again, here is the log:
```
2022-02-02T17:33:02Z POTENTIAL DEADLOCK DETECTED
2022-02-02T17:33:02Z Previous lock order was:
2022-02-02T17:33:02Z pnode->cs_sendProcessing net.cpp:2029 (in thread msghand)
2022-02-02T17:33:02Z cs_main net_processing.cpp:3682 (TRY) (in thread msghand)
2022-02-02T17:33:02Z pto->cs_inventory net_processing.cpp:3898 (in thread msghand)
2022-02-02T17:33:02Z (1) pto->m_tx_relay->cs_tx_inventory net_processing.cpp:3912 (in thread msghand)
2022-02-02T17:33:02Z pto->m_tx_relay->cs_filter net_processing.cpp:3984 (in thread msghand)
2022-02-02T17:33:02Z (2) cs txmempool.cpp:817 (in thread msghand)
2022-02-02T17:33:02Z Current lock order is:
2022-02-02T17:33:02Z m_cs_chainstate validation.cpp:2902 (in thread msghand)
2022-02-02T17:33:02Z cs_main validation.cpp:2919 (in thread msghand)
2022-02-02T17:33:02Z (2) ::mempool.cs validation.cpp:2919 (in thread msghand)
2022-02-02T17:33:02Z cs_vNodes ./net.h:215 (in thread msghand)
2022-02-02T17:33:02Z (1) m_tx_relay->cs_tx_inventory ./net.h:972 (in thread msghand)
Assertion failed: detected inconsistent lock order at sync.cpp:119, details in debug log.
./start-btcsqd.sh: line 1: 849357 Aborted (core dumped) ./btcsqd -datadir="./data"
```
