### ISSUE TITLE
No new blocks are added without setting connect= or addnode= in conf

### ISSUE THREAD

**Issue by Leonardiae** [VeriBlock/vbk-ri-btc#597]
When I run with connect=x.x.x.x I find peers.
When I run with addnode=x.x.x.x I find peers
When I run without connect= / addnode= in btcsq.conf I don't find peers and getpeerinfo shows no result.

**Comment by Warchant** [comment]
Duplicate of https://github.com/VeriBlock/vbk-ri-btc/issues/593
