### ISSUE TITLE
Avoid unnecessary POP fork resolutions 

### ISSUE THREAD

**Issue by Mr-Leshiy** [VeriBlock/vbk-ri-btc#604]
POP fork resolution (FR) is executed for blocks that cannot be connected to the current chain. Eg we want to connect block 203 and block 202 is missing but block 202 header exists.
We want to execute POP FR on connecting blocks only.

**Comment by Warchant** [comment]
What is the status? @blackyblack

**Comment by blackyblack** [comment]
> What is the status? @blackyblack

Done.
