### ISSUE TITLE
Fix Linux asan CI failing

### ISSUE THREAD

**Issue by Mr-Leshiy** [VeriBlock/vbk-ri-btc#614]
Currently we have the following job failing in the master branch https://github.com/VeriBlock/vbk-ri-btc/runs/4252725666?check_suite_focus=true. Need to fix `linux-asan` action.

**Comment by blackyblack** [comment]
Bitcoin QT actually contains memory leaks:
```
QPropertyAnimation* animation = new QPropertyAnimation(this, "pos");
animation->setDuration(300);
```
We do not want to fix original Bitcoin code so I propose to remove QT from linux-asan CI task.
