### ISSUE TITLE
ABFI Status not showing correctly on QT Wallet Transaction Details

### ISSUE THREAD

**Issue by overcookedpanda** [VeriBlock/vbk-ri-btc#621]
Within the config file you can specify `bfiendpoint=https://testnet.abfi.veriblock.org/`

When someone clicks on the transaction details, it should take the altchain ID (%1) and the txid (%2) and formulate the url as below:

https://testnet.abfi.veriblock.org/%1/chains/transactions/%2

It should then show the 'bitcoinFinality' of the transaction that it gets back from the API.

There are no errors in the log about the API call, and if you manually call the API, you get a valid response.

**Comment by timstall** [comment]
This corresponds to what one would see in the explorer, such as:
https://testnet.explore.vbtc.veriblock.org/tx/f445862c48bebe032cc9c9d4792af59bbdb3eff2132b428db892743efcff8b08
![image](https://user-images.githubusercontent.com/9978739/144896677-fe9c428f-4f47-4ace-9d7f-5805afcd6175.png)

Full API:
https://testnet.abfi.veriblock.org/16579303907010303/chains/transactions/f445862c48bebe032cc9c9d4792af59bbdb3eff2132b428db892743efcff8b08

Likely code section:
https://github.com/VeriBlock/vbk-ri-btc/blob/master/src/qt/transactiondesc.cpp#L123-L198
