### ISSUE TITLE
Assert error when zmqpubrawblock/zmqpubhashblock port is in use

### ISSUE THREAD

**Issue by Leonardiae** [VeriBlock/vbk-ri-btc#628]
When the zmqpubrawblock / zmqpubhashblock port is already in use (by another BTCSQ daemon) then an assertion failed error appears. 

```
Assertion failed!

Program: ...
File: zmq/zmqpublishnotifier.cpp
Line: 115

Expression: psocket
```

I'd expect a human readable error like when the rpcport is in use:

`Error: Unable to start HTTP server. See debug log for details.`

**Comment by Warchant** [comment]
Yeah... must be something we inherited from BTC
